// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu0e9Z4cq31giAm9ezJBMvyxU-437n-j0',
    appId: '1:333326594:web:94480e1b6848d6dc09fa1b',
    messagingSenderId: '333326594',
    projectId: 'doxmessenger-e93d6',
    authDomain: 'doxmessenger-e93d6.firebaseapp.com',
    storageBucket: 'doxmessenger-e93d6.firebasestorage.app',
    measurementId: 'G-0Y35JCB65S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92tTPhvkOY7IWywuvcNttRqm98YhfgHs',
    appId: '1:333326594:android:9a187d79158ee50509fa1b',
    messagingSenderId: '333326594',
    projectId: 'doxmessenger-e93d6',
    storageBucket: 'doxmessenger-e93d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0ORxt5g-3NfLru6PnYGai1X_IB_lgoY',
    appId: '1:333326594:ios:f8bd448a3f81cfeb09fa1b',
    messagingSenderId: '333326594',
    projectId: 'doxmessenger-e93d6',
    storageBucket: 'doxmessenger-e93d6.firebasestorage.app',
    iosBundleId: 'com.example.dox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK0ORxt5g-3NfLru6PnYGai1X_IB_lgoY',
    appId: '1:333326594:ios:f8bd448a3f81cfeb09fa1b',
    messagingSenderId: '333326594',
    projectId: 'doxmessenger-e93d6',
    storageBucket: 'doxmessenger-e93d6.firebasestorage.app',
    iosBundleId: 'com.example.dox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu0e9Z4cq31giAm9ezJBMvyxU-437n-j0',
    appId: '1:333326594:web:1d51c1c0d9dc432509fa1b',
    messagingSenderId: '333326594',
    projectId: 'doxmessenger-e93d6',
    authDomain: 'doxmessenger-e93d6.firebaseapp.com',
    storageBucket: 'doxmessenger-e93d6.firebasestorage.app',
    measurementId: 'G-GFXPR09EW3',
  );
}
